[general]
import = [
  "~/.config/MyConfigFiles/tokyo_night.toml"
]
[window]
opacity=0.98
blur=true
startup_mode="Maximized"
decorations="none"

[font]
size=21
normal={family ="IosevkaTermslab Nerd Font", style="Regular"}

[cursor]
style= {shape="Underline", blinking="On"}
