[general]
import = [
  "~/.config/dotfiles/tokyo_night.toml"
]
[window]
opacity=0.85
blur=true
startup_mode="Maximized"
decorations="none"

[font]
size=16
normal={family ="IosevkaTermslab Nerd Font", style="Bold"}

[cursor]
style= {shape="Underline", blinking="On"}
